package:
  name: bcpandas
  version: "0.1.4"

source:
  url: https://github.com/yehoshuadimarsky/bcpandas/archive/0.1.4.tar.gz
  sha256: af9328f85550bcf80606df33e357825d0a4d14a64feabf37a48731861d0256bf

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
  
  run: 
    - python>=3.6 
    - pandas>=0.22 
  
test:
  imports:
    - bcpandas

about:
  home: https://pypi.org/project/bcpandas
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Wrapper around BCP to transfer data between pandas and SQL Server.
  description: |
    High-level wrapper around BCP for high performance data transfers between pandas and SQL Server. 
    No knowledge of BCP required!!
  doc_url: https://github.com/yehoshuadimarsky/bcpandas
  dev_url: https://github.com/yehoshuadimarsky/bcpandas

extra:
  recipe-maintainers:
    - yehoshuadimarsky
