{% set name = "bcpandas" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 434a99fcdd760b91291e1471c2ed5e592eda23a220b729c5fe69dab087272a6b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools

  run:
    - python >=3.6
    - pandas >=0.19
    - pyodbc
    - sqlalchemy >=1.0

test:
  imports:
    - bcpandas

about:
  home: https://pypi.org/project/bcpandas
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Wrapper around BCP to transfer data between pandas and SQL Server.
  description: |
    High-level wrapper around BCP for high performance data transfers between pandas and SQL Server. 
    No knowledge of BCP required!!
  doc_url: https://github.com/yehoshuadimarsky/bcpandas
  dev_url: https://github.com/yehoshuadimarsky/bcpandas

extra:
  recipe-maintainers:
    - borchero
    - yehoshuadimarsky
    - owenlamont
