package:
  name: bcpandas
  version: "0.1.6"

source:
  url: https://github.com/yehoshuadimarsky/bcpandas/archive/0.1.6.tar.gz
  sha256: a67a8e6737a1f54c5bf9a6df8e6f9d2dea2f18cac873a35106bb0a7c2a2bb4e6

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python>=3.6
    - pip
    - setuptools
  
  run: 
    - python>=3.6 
    - pandas>=0.22 
  
test:
  imports:
    - bcpandas

about:
  home: https://pypi.org/project/bcpandas
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Wrapper around BCP to transfer data between pandas and SQL Server.
  description: |
    High-level wrapper around BCP for high performance data transfers between pandas and SQL Server. 
    No knowledge of BCP required!!
  doc_url: https://github.com/yehoshuadimarsky/bcpandas
  dev_url: https://github.com/yehoshuadimarsky/bcpandas

extra:
  recipe-maintainers:
    - yehoshuadimarsky
