{% set name = "bcpandas" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 48e8a55e5a199e32f8af8a8511707c0ac69fdcc7878b32dcacb79708d101d8d1

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6, <3.8
    - pip
    - setuptools
  
  run: 
    - python >=3.6, <3.8
    - pandas >=0.19 
    - pyodbc 
    - sqlalchemy >=1.1.4 
  
test:
  imports:
    - bcpandas

about:
  home: https://pypi.org/project/bcpandas
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Wrapper around BCP to transfer data between pandas and SQL Server.
  description: |
    High-level wrapper around BCP for high performance data transfers between pandas and SQL Server. 
    No knowledge of BCP required!!
  doc_url: https://github.com/yehoshuadimarsky/bcpandas
  dev_url: https://github.com/yehoshuadimarsky/bcpandas

extra:
  recipe-maintainers:
    - yehoshuadimarsky
