travis:
  secure:
    BINSTAR_TOKEN: OSAiunM8egw/cFV+xD4lBGsKPmN05WLQ9IybrqJpIAeWpbiDSkdMOYoeZu25dkvRIbtRq3oqEaOYWe+hSZXDgzIih5OSNjRbDulS86Qxf+HPDUGQ97gHxbe2amreZW3QGXOrPrDS1o52E1La+JK0V64ah5BsofZqXq+7L8P0gfoBhj2LXHEnAJ2eKdCwW6o88GjNpRs/xJnaUUrzjlrp2EIemaxCw/bL1zUThpxgWahXHqrzWuXJEoyYM1Eqe4yBGzxZE6Xlk3RnqwTawNTax01Xpn1/oBVDzoOLN69UKREDUVaIZ7vRZLXxOfJIB42Vbu4hcnjGC42o2ItXnY0z85/taBCN9ZErZgWEO/JExCI5f0ZbxSvrsihh4wHMtAl8gSD1hqaG+1KGc276I0qqc/SMv3Mf5OEahfU2ejWrSWTwd5eAXneWb7ftxBTWtxLpHB3pfOJgNFxqqYdG5RTozkY/5sw8mi2UcaGP4RlXG1v9eZ4gqTiAou4FAvsHeXvSthmNjBaZnMH4tJ+iYbRsWGqAhUmIgUttRHczX8wlTp84npQbb7aDddijp/Btha8VvYfXhbniF03XZvaucI9qLrRrxVou3qXt8ZFe4qm0VqzaNVMxRijtQcQLpi4jgIoYA92aoTOOGIzSRXl7lY6b9yFRSKCSKFN1eg+mIr40o7M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
